export const countryCode = {
  england: "gb",
  scotland: "gb-sct",
  wales: "gb-wls",

  france: "fr",
  germany: "de",
  spain: "es",
  portugal: "pt",
  italy: "it",
  netherlands: "nl",
  belgium: "be",
  croatia: "hr",
  switzerland: "ch",
  denmark: "dk",
  serbia: "rs",
  poland: "pl",
  austria: "at",
  czechia: "cz",
  hungary: "hu",
  ukraine: "ua",
  norway: "no",
  sweden: "se",
  turkey: "tr",

  brazil: "br",
  argentina: "ar",
  uruguay: "uy",
  colombia: "co",
  peru: "pe",
  ecuador: "ec",
  chile: "cl",
  paraguay: "py",
  venezuela: "ve",
  
  curacao: "cw",
  capeverde: "cv",
  bosniaandherzegovina: "ba",
  newzealand: "nz",
  haiti: "ht",

  
  usa: "us",
  canada: "ca",
  mexico: "mx",
  costarica: "cr",
  panama: "pa",
  jamaica: "jm",

  morocco: "ma",
  senegal: "sn",
  nigeria: "ng",
  ghana: "gh",
  cameroon: "cm",
  tunisia: "tn",
  egypt: "eg",
  algeria: "dz",
  southafrica: "za",
  ivorycoast: "ci",
  drcongo: "cd",

  japan: "jp",
  southkorea: "kr",
  saudiarabia: "sa",
  iran: "ir",
  qatar: "qa",
  australia: "au",
  uzbekistan: "uz",
  iraq: "iq",
  jordan: "jo",
  uae: "ae",
  india: "in",
  china: "cn",
};